import AppKit
import ApplicationServices
import Carbon.HIToolbox
import MyWhispererCore

/// Puts text at the cursor of the frontmost app by pasting it, then restores
/// whatever was on the clipboard before.
final class TextInserter: TextInserting {
    var restoreClipboard: () -> Bool = { true }

    func insert(_ text: String) async -> InsertOutcome {
        guard !text.isEmpty else { return .inserted }
        let pasteboard = NSPasteboard.general

        // Without Accessibility we can't synthesize ⌘V; leave it on the clipboard.
        guard AXIsProcessTrusted(), hasFocusedElement() else {
            Self.copy(text, to: pasteboard, transient: false)
            return .copiedToClipboard
        }

        let saved = restoreClipboard() ? Self.snapshot(pasteboard) : nil
        Self.copy(text, to: pasteboard, transient: true)
        let changeCount = pasteboard.changeCount

        Self.postPaste()

        // Give the target app time to read the clipboard before restoring it.
        try? await Task.sleep(for: .milliseconds(300))
        if let saved, pasteboard.changeCount == changeCount {
            Self.restore(saved, to: pasteboard)
        }
        return .inserted
    }

    /// Copies text for the user to paste themselves (menu, history, fallback).
    static func copyToClipboard(_ text: String) {
        copy(text, to: .general, transient: false)
    }

    private func hasFocusedElement() -> Bool {
        let system = AXUIElementCreateSystemWide()
        AXUIElementSetMessagingTimeout(system, 0.2)
        var focused: CFTypeRef?
        let result = AXUIElementCopyAttributeValue(system, kAXFocusedUIElementAttribute as CFString, &focused)
        // Some apps don't report focus over AX but still accept paste; only
        // treat an explicit "nothing focused" as a reason not to paste.
        return result != .noValue
    }

    // MARK: Pasteboard

    private static func copy(_ text: String, to pasteboard: NSPasteboard, transient: Bool) {
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        if transient {
            // nspasteboard.org conventions: clipboard managers skip these.
            for type in ["org.nspasteboard.TransientType", "org.nspasteboard.ConcealedType", "org.nspasteboard.AutoGeneratedType"] {
                item.setData(Data(), forType: NSPasteboard.PasteboardType(type))
            }
        }
        pasteboard.writeObjects([item])
    }

    private static func snapshot(_ pasteboard: NSPasteboard) -> [[NSPasteboard.PasteboardType: Data]] {
        (pasteboard.pasteboardItems ?? []).map { item in
            var entry: [NSPasteboard.PasteboardType: Data] = [:]
            for type in item.types {
                if let data = item.data(forType: type) { entry[type] = data }
            }
            return entry
        }
    }

    private static func restore(_ items: [[NSPasteboard.PasteboardType: Data]], to pasteboard: NSPasteboard) {
        pasteboard.clearContents()
        guard !items.isEmpty else { return }
        let restored = items.map { entry -> NSPasteboardItem in
            let item = NSPasteboardItem()
            for (type, data) in entry { item.setData(data, forType: type) }
            return item
        }
        pasteboard.writeObjects(restored)
    }

    // MARK: Keystroke

    private static func postPaste() {
        // A private state source: the user's physical modifiers don't leak in.
        let source = CGEventSource(stateID: .privateState)
        let key = CGKeyCode(keyCodeForV())
        let down = CGEvent(keyboardEventSource: source, virtualKey: key, keyDown: true)
        let up = CGEvent(keyboardEventSource: source, virtualKey: key, keyDown: false)
        down?.flags = .maskCommand
        up?.flags = .maskCommand
        down?.post(tap: .cghidEventTap)
        up?.post(tap: .cghidEventTap)
    }

    /// The key that types "v" in the current layout (Dvorak, AZERTY, …), so
    /// ⌘V means paste everywhere. Falls back to the ANSI position.
    private static func keyCodeForV() -> Int {
        guard let source = TISCopyCurrentKeyboardLayoutInputSource()?.takeRetainedValue(),
              let dataRef = TISGetInputSourceProperty(source, kTISPropertyUnicodeKeyLayoutData) else {
            return kVK_ANSI_V
        }
        let layoutData = unsafeBitCast(dataRef, to: CFData.self)
        guard let bytes = CFDataGetBytePtr(layoutData) else { return kVK_ANSI_V }
        let layout = UnsafeRawPointer(bytes).assumingMemoryBound(to: UCKeyboardLayout.self)

        for code in 0..<128 {
            var deadKeys: UInt32 = 0
            var length = 0
            var chars = [UniChar](repeating: 0, count: 4)
            let status = UCKeyTranslate(layout, UInt16(code), UInt16(kUCKeyActionDisplay), 0,
                                        UInt32(LMGetKbdType()), OptionBits(kUCKeyTranslateNoDeadKeysBit),
                                        &deadKeys, chars.count, &length, &chars)
            if status == noErr, length == 1, chars[0] == UniChar(("v" as Unicode.Scalar).value) {
                return code
            }
        }
        return kVK_ANSI_V
    }
}
